<?php

/**
 * @file
 * Contains bt_commerce.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bt_commerce_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bt_commerce module.
    case 'help.page.bt_commerce':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_local_tasks_alter().
 */
function bt_commerce_local_tasks_alter(&$local_tasks) {
  $local_tasks['entity.commerce_order.collection']['base_route'] = 'bt_commerce.dashboard';
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function bt_commerce_menu_links_discovered_alter(&$links) {
  $links['entity.commerce_order.collection']['parent'] = 'bt_commerce.dashboard_menu';
  $links['entity.commerce_product_attribute.collection']['parent'] = 'bt_commerce.dashboard_menu';
  $links['entity.commerce_product.collection']['parent'] = 'bt_commerce.dashboard_menu';
  $links['entity.commerce_promotion.collection']['parent'] = 'bt_commerce.dashboard_menu';
}
